### PR TITLE
remove testutils from chronicles

### PR DESCRIPTION
**Pull request by disruptek**
A pull to remove testutils and see how the CI likes it.  I expect you'll want to move testutils under the status-im org aegis, first.

### CODE REVIEW

**Comment by disruptek** [comment]
I'm doing something wrong, but I don't know what; I've never used Appveyor before.  Seems like it can't run testrunner but it's not clear if it's a path problem or something else.

**Comment by jangko** [comment]
probably related to Nim-stdlib `startProcess` nim-lang/Nim#8913 issue.

tested solution:
- move testrunner.exe to %USERPROFILE%\.nimble\bin
- avoid using testrunner.cmd to execute testrunner.exe

**Comment by disruptek** [comment]
I think my take-away here is that `testrunner.cmd` is a batch file and Windows cannot execute it.

But I'm not clear on where `testrunner.cmd` comes from, if it even exists.  I think `nimble` should be installing `testrunner.exe` to `%USERPROFILE%\.nimble\bin` because it seems to install it successfully on Linux CI.

**Comment by jangko** [comment]
From nimble readme:

> In this case when nimble install is invoked, Nimble will build the main.nim file, copy it into $nimbleDir/pkgs/pkgname-ver/ and subsequently create a symlink to the binary in $nimbleDir/bin/. On Windows a stub .cmd file is created instead.

in `chronicles.nimble` you can use:

```Nim
  when defined(windows):
    exec "cmd.exe /C testrunner.cmd tests"
  else:
    exec "testrunner.cmd tests"
```

**Comment by disruptek** [comment]
Awesome, thanks!  Let's see if that helps... :wink:

**Comment by zah** [comment]
Awesome! Thanks @disruptek and @jangko

**Pull request merged**
